# Project information
site_name: Luvascript Documentation
site_url: https://lucr4ft.github.io/luvascript-compiler/
site_author: Luca Lewin

# Repository
repo_name: lucr4ft/luvascript-compiler
repo_url: https://github.com/lucr4ft/luvascript-compiler
edit_uri: ""

copyright: Copyright &copy; 2022 Luca Lewin

theme:
  name: material

    # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    scheme: slate
    primary: purple
    accent: purple

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started: getting-started/index.md
  - Installation:
    - installation/index.md
    - Install on Windows: installation/windows.md
    - Install on Linux: installation/linux.md
    - Install on MacOS: installation/macos.md
  - Compiler:
    - Overview: compiler/index.md
    - Options: compiler/options.md
    - Conventions:
      - compiler/conventions/index.md
      - Luvascript Naming Convention: compiler/conventions/luvascript-naming-convention.md
    - Compiler Messages: compiler/messages/index.md
    - Source Documentation:
      - compiler/source-docs/index.md
  - Language Reference:
    - Overview: language-reference/index.md
    - Order of Operations: language-reference/order-of-operations.md
    - Datatypes: language-reference/datatypes.md
    - External Functions: language-reference/external-functions.md
    - Inline Assembly: language-reference/inline-assembly.md
  - Language Specifications:
    - Overview: language-specifications/index.md
    - Version 0.1.0: language-specifications/0.1.0.md
