#ifndef LUVA_REGISTER_H
#define LUVA_REGISTER_H

#include <types/variable.h>

typedef enum Register {
	REGISTER_NONE,
	REGISTER_EAX,
	REGISTER_EBX,
	REGISTER_ECX,
	REGISTER_EDX,
	REGISTER_ESI,
	REGISTER_EDI,
	REGISTER_EBP,
	REGISTER_ESP,
	REGISTER_EIP,
	REGISTER_R8,
	REGISTER_R9,
	REGISTER_R10,
	REGISTER_R11,
	REGISTER_R12,
	REGISTER_R13,
	REGISTER_R14,
	REGISTER_R15,
	REGISTER_XMM0,
	REGISTER_XMM1,
	REGISTER_XMM2,
	REGISTER_XMM3,
	REGISTER_XMM4,
	REGISTER_XMM5,
	REGISTER_XMM6,
	REGISTER_XMM7,
	REGISTER_XMM8,
	REGISTER_XMM9,
	REGISTER_XMM10,
	REGISTER_XMM11,
	REGISTER_XMM12,
	REGISTER_XMM13,
	REGISTER_XMM14,
	REGISTER_XMM15,
	REGISTER_COUNT
} Register;

char *getRegisterWithOpCodeSize(Register reg, int opCodeSize);

#endif